### ISSUE TITLE
Switch to Slack (from Gitter)

### ISSUE THREAD

**Issue by BreiteSeite** [prooph/docs#3]
Hi,

i don't know where to open this, but as this repository contains the reference to the prooph gitter chat in the documentation, i thought it would be appropriate to discuss this here.

I'm semi-active in the prooph gitter chat. I don't use gitter much. I think the prooph 'support chat' is more like a community chat.

The reason i'm asking because i noticed sometimes there are multiple topics ongoing in the gitter chat and it gets sometimes a bit difficult to see whats going on and who is responding to which message. It's because it seems like gitter is neither supporting channels nor threads.

I'll propose a switch to slack, because people that are already active in the chats of [symfony](https://symfony.com/support), [laravel](https://larachat.co) or [zend](https://zendframework-slack.herokuapp.com) ([their reasons to use slack](https://framework.zend.com/blog/2017-04-04-newsletter-and-slack.html)) are using slack already.

Slack supports channels (like one to ask about prooph components, one about generic architecturial questions, one for random small talk, one for announcements from the team, ...) and threads (easier to follow a single conversation) as well as referencing to messages.

In my opinion, that would really helping making chatting about prooph and it's concepts much more enjoyable and thus help to get more/better support by the community.

Let me know what you think.

**Comment by prolic** [comment]
We had this slack vs gitter discussion already multiple times. First, slack is not for free, if you want to preserve that chat history, you have to pay. That fact doesn't change for open source projects. Second: everyone with a github account can login to gitter and use it right away. I used slack for work-related projects, so please don't tell me "but with slack you can X" - I know, but it's not free and gitter is. So that's why I am against slack, but if enough people are willing to move, I will not post a blocker-veto.

**Comment by codeliner** [comment]
@BreiteSeite Is it possible to enable Github login for slack? That would be one precondition. The second precondition would be that someone pays the slack account. 

**Why Github login?**
I really don't want to maintain slack. We are not Zend or SensioLabs. I'll block any additional (unpaid) work on my desk because I already spend a lot of spare time for prooph. More is not possible at the moment. 

Gitter is easy because it seamlessly integrates with Github. I have no additional work with it. 
- no invitations
-  orga activity integrated without additional set up
- I can ping people using their Github name (huge win for me)

**Chat history is important**
I need the history at least for one-to-one chats, which would get lost due to 10,000 messages limit, too.

Maybe we can switch to slack later, but at the moment the project is mainly driven by open source contributions so we have to use simple and free tools.

**Comment by codeliner** [comment]
I want to try https://waffle.io/. They have a free plan for open source projects and you can connect many repos with a waffle board. I hope that we get more overview and better planing with waffle. Longer and important discussions can be moved to github issues then. It's the better option because discussions can be completely async and can take weeks. They are public, you can link to comments, etc.
